name: cuberto_bottom_bar
description: An animated bottom navigation bar supporting drawer icon at start or end or can be used with the drawer icon and is provided with 2 different styles.
version: 3.1.0
homepage: https://github.com/kushalmahapatro/cuberto_bottom_bar

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
